### ISSUE TITLE
E55 vs ConceptScheme

### ISSUE THREAD

**Issue by VladimirAlexiev** [sapa/spa-vocabulary#1]
```ttl
spav:ha a crm:E55_Type,
        skos:ConceptScheme
```
However, crm:E55_Type corresponds to skos:Concept not skos:ConceptScheme. The latter corresponds to CRM authority document. 

If you use some CRM class, you better also use CRM properties. Then you would basically replicate the data in skos and crm, 
and what is the benefit of that?  Since most vocabularies in the world are represented in skos,  I think keep skos only.

**Comment by birk** [comment]
I moved the `crm:E55_Type` and would postpone a decision on whether to drop it all together. https://github.com/sapa/spa-vocabulary/commit/e85f856bb75527357e7b85c62e5bff4bcb4e0f8f
