### ISSUE TITLE
spav:rt (oubli)

### ISSUE THREAD

**Issue by b2d3c** [sapa/spa-vocabulary#13]
Cher @tfrancart 

Dans le cadre de ma relecture de votre travaux du second mandat, j'ai pu relever que : 

Le vocabulaire **rt** n’est pas complet sur le minisite : http://vocab.performing-arts.ch/vocabulary/rt/ et il faudrait aussi mettre à jour dans SPAP car les entités ne sont plus raccrochées au vocabulaire : https://www.performing-arts.ch/resource/spav:rt?view=statements . Cela concerne :

https://www.performing-arts.ch/resource/spav:rtac
https://www.performing-arts.ch/resource/spav:rtsp
https://www.performing-arts.ch/resource/spav:rtmi

Visiblement, cela provient du fait que les entrées n'étaient pas complètes dans le tableur en ligne.

**Comment by tfrancart** [comment]
@b2d3c j'attends ton feu vert pour recharger les vocabulaires en prod.

**Comment by b2d3c** [comment]
Feu vert! Merci du travail.

**Comment by tfrancart** [comment]
@b2d3c la mise à jour est faite sur la prod

**Comment by b2d3c** [comment]
Merci !
