### ISSUE TITLE
Coreference to AAT

### ISSUE THREAD

**Issue by VladimirAlexiev** [sapa/spa-vocabulary#2]

**Comment by birk** [comment]
There are references to AAT. However, in a lot of cases AAT is so incomplete in regard to our subjects that it feels more like a pro forma exercise than an actual feature to do the mapping. Look at `medium` e.g.: https://sapa.github.io/spa-vocabulary/#http://vocab.performing-arts.ch/fv

**Comment by VladimirAlexiev** [comment]
I think that pharpring at Getty dot edu will take submissions. But you need
to prepare definitions and sources.
