### ISSUE TITLE
Activity vs actor role

### ISSUE THREAD

**Issue by VladimirAlexiev** [sapa/spa-vocabulary#4]
The activity scheme has concepts explaining a duality: activity (e.g. choreography) vs actor role (eg choreographer). Currently the latter is captured only in rdfs:comment, and not in a pure form (is choreographer of).
Devise a better structured representation, include more labels (including multiple languages) , capture the relations between these labels.

**Comment by birk** [comment]
`rdfs:comment` only functions as a temporary link to the data model, which represented activities in a different way. Overall, this part is less than an draft at the moment.

**Comment by VladimirAlexiev** [comment]
Please keep this open until a better solution is devised

**Comment by birk** [comment]
I clarified how the temporary `rdfs:comment` should be understood. https://github.com/sapa/spa-vocabulary/commit/89f904d6a9a915757ac389c0958d2287375f408f
