### ISSUE TITLE
Mise à jour du vocabulaire : df

### ISSUE THREAD

**Issue by b2d3c** [sapa/spa-vocabulary#8]
Cher @tfrancart ,

Le vocabulaire df a été mis à jour dans la tabel en ligne. J'ai introduit aussi des remarques là où nous avons créer des doublons non nécessaires.

Puis-je te demander de mettre à jour les vocabulaires sur DEV?

Je reste à disposition pour toutes questions.

**Comment by tfrancart** [comment]
C'est fait

**Comment by b2d3c** [comment]
Merci du déploiement en PROD !
